.TH "main.c" 3 "Quinta, 13 de Fevereiro de 2014" "Documentação" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'busca\&.h'\fP
.br

.SS "Funções"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Documentação das funções"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definido na linha 28 do ficheiro main\&.c\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Documentação a partir do código fonte\&.
